// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.HttpRestClient.BodyFormat")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientResponse`1.Failure(System.Exception,System.Net.HttpStatusCode)~Xpandables.Net.HttpRestClient.HttpRestClientResponse{`0}")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientResponse`1.Failure(Xpandables.Net.HttpRestClient.HttpRestClientException,System.Net.HttpStatusCode)~Xpandables.Net.HttpRestClient.HttpRestClientResponse{`0}")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientResponse`1.Success(`0,System.Net.HttpStatusCode)~Xpandables.Net.HttpRestClient.HttpRestClientResponse{`0}")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientResponse`1.Success(System.Net.HttpStatusCode)~Xpandables.Net.HttpRestClient.HttpRestClientResponse{`0}")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:Xpandables.Net.HttpRestClient.IPLocation.CountryFlagUrl")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientExtensions.GetHttpRequestMessageAsync``1(Xpandables.Net.HttpRestClient.HttpRestClientAttribute,``0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpRequestMessage}")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:Xpandables.Net.HttpRestClient.HttpRestClientResponse.Headers")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.QrCodes.QrCodeImageGenerator.Generate(System.Collections.Generic.IEnumerable{System.String},System.Drawing.Color,System.Drawing.Color,System.Int32)~System.Collections.Generic.IEnumerable{System.Byte[]}")]
[assembly: SuppressMessage("Style", "IDE0057:Use range operator", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.QrCodes.Presenter.QRCodeGenerator.GenerateQrCode(System.String,Xpandables.Net.QrCodes.Presenter.QRCodeGenerator.ECCLevel,System.Int32)~Xpandables.Net.QrCodes.Presenter.QrCodeData")]
[assembly: SuppressMessage("Naming", "ET001:Type name does not match file name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.Correlation.AsyncCorrelationPostEvent")]
[assembly: SuppressMessage("Naming", "ET001:Type name does not match file name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.Correlation.AsyncCorrelationRollbackEvent")]
[assembly: SuppressMessage("Naming", "ET001:Type name does not match file name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.Correlation.CorrelationPostEvent")]
[assembly: SuppressMessage("Naming", "ET001:Type name does not match file name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.Correlation.CorrelationRollbackEvent")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.IHttpRestClientHandler.GetResponseAsync``2(System.Net.Http.HttpResponseMessage,System.Func{System.IO.Stream,``0})~System.Threading.Tasks.Task{Xpandables.Net.HttpRestClient.HttpRestClientResponse{``0}}")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.Data.Executables.DataExecutableTable.ExecuteAsync(Xpandables.Net.Data.Executables.DataExecutableContext)~System.Threading.Tasks.Task{Xpandables.Net.Optionals.Optional{System.Data.DataTable}}")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.Data.Executables.DataExecutableSingle`1.ExecuteAsync(Xpandables.Net.Data.Executables.DataExecutableContext)~System.Threading.Tasks.Task{Xpandables.Net.Optionals.Optional{`0}}")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.Data.Executables.DataExecutableProcedure.ExecuteAsync(Xpandables.Net.Data.Executables.DataExecutableContext)~System.Threading.Tasks.Task{Xpandables.Net.Optionals.Optional{System.Int32}}")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.Data.Executables.DataExecutableMapperFuncProc`1.ExecuteMappedAsync(Xpandables.Net.Data.Executables.DataExecutableContext)~System.Collections.Generic.IAsyncEnumerable{`0}")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.Data.Connections.DataConnectionContextProvider.SpeedSqlServerResultAsync(System.Data.Common.DbConnection)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "SecurityIntelliSenseCS:MS Security rules violation", Justification = "<Pending>", Scope = "member", Target = "~M:Xpandables.Net.HttpRestClient.HttpRestClientExtensions.GetHttpRequestMessageAsync``1(Xpandables.Net.HttpRestClient.HttpRestClientAttribute,``0,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpRequestMessage}")]
[assembly: SuppressMessage("Naming", "ET001:Type name does not match file name", Justification = "<Pending>", Scope = "type", Target = "~T:Xpandables.Net.Http.HttpTokenAccessorDelegate")]
