//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpandables.Net.Api.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpandables.Net.Api.Localization.LocalizationService", typeof(LocalizationService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Basic invalide..
        /// </summary>
        public static string AUTHENTICATION_BASIC_INVALID {
            get {
                return ResourceManager.GetString("AUTHENTICATION_BASIC_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token d&apos;authorisation attendu.
        /// </summary>
        public static string AUTHOR_TOKEN_EXPECTED {
            get {
                return ResourceManager.GetString("AUTHOR_TOKEN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe temporaire..
        /// </summary>
        public static string MAIL_PWD_TEMPORARY {
            get {
                return ResourceManager.GetString("MAIL_PWD_TEMPORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nouveau mot de passe : {0}.
        /// </summary>
        public static string MAIL_PWD_TEMPORARY_MSG {
            get {
                return ResourceManager.GetString("MAIL_PWD_TEMPORARY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone et/ou email existe déjà..
        /// </summary>
        public static string PHONE_EMAIL_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("PHONE_EMAIL_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone invalide..
        /// </summary>
        public static string PHONE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone et/ou mot de passe invalide..
        /// </summary>
        public static string PHONE_PWD_INVALID {
            get {
                return ResourceManager.GetString("PHONE_PWD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image invalide..
        /// </summary>
        public static string PICTURE_INVALID {
            get {
                return ResourceManager.GetString("PICTURE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de compte invalide..
        /// </summary>
        public static string REGISTER_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;authentification envoyé à votre numéro de téléphone.
        /// </summary>
        public static string TWO_FACTOR_AUTHEN__SENT_OK {
            get {
                return ResourceManager.GetString("TWO_FACTOR_AUTHEN__SENT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;authentification invalide.
        /// </summary>
        public static string TWO_FACTOR_AUTHEN_CODE_INVALID {
            get {
                return ResourceManager.GetString("TWO_FACTOR_AUTHEN_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;authentification erreur d&apos;envoi ou de vérification. Réessayer.
        /// </summary>
        public static string TWO_FACTOR_AUTHEN_ERROR {
            get {
                return ResourceManager.GetString("TWO_FACTOR_AUTHEN_ERROR", resourceCulture);
            }
        }
    }
}
